### ISSUE TITLE
Update FAQ entry about helper for recording violation entries

### ISSUE THREAD

**Issue by str4d** [mozilla/cargo-vet#154]
The FAQ [states](https://mozilla.github.io/cargo-vet/design-choice-faq.html#why-is-there-no-helper-for-recording-violation-entries) that there is no `cargo vet record-violation` as an analogue to `cargo vet certify`, and gives reasons why. However, `cargo-vet` as installed from this repository has a `cargo vet add-violation` command that appears to be precisely this helper.

The FAQ entry should be either removed, or updated with the relevant context for `cargo vet add-violation`.

**Comment by Gankra** [comment]
add-unaudited and add-violation are both "plumbing" commands I added for testing/experimentation, it's unclear if they should be visible/exposed longterm

**Comment by bholley** [comment]
I think this is a fair point. The FAQ entry predates both our switch to semver's VersionReq for violation entries, and @Gankra's addition of the command which turned out to be much less of a hassle than I expected (seems like as long as you quote the VersionReq no other special escaping is needed).

I'll go ahead and remove the FAQ entry.

**Comment by bholley** [comment]
I also renamed `add-violation` to `record-violation` here: https://github.com/mozilla/cargo-vet/commit/88c6957699ecf08b2d9985edea9fa2b02cc6e8eb
