### ISSUE TITLE
Should organizations wait for `cargo vet aggregate` to exist before submitting PRs to `registry.toml`?

### ISSUE THREAD

**Issue by str4d** [mozilla/cargo-vet#157]
I'm starting an audit file that would currently live at https://raw.githubusercontent.com/zcash/zcash/master/qa/supply-chain/audits.toml which is at the "top level" of our repository tree, but it would likely be replaced with a file in an automated repository once `cargo vet aggregate` means we can split our audits across several repos.

Put another way, is `registry.toml` always queried live (modulo `cargo vet --locked`), or is it baked into the compiled `cargo-vet` binary? The former means that registry URLs can just be updated or replaced without needing redirects (which are at a minimum non-trivial for hosted git repos). The latter would mean organizations need to be more careful about how registry URLs are migrated.

**Comment by bholley** [comment]
The plan is for it to be queried live rather than baked into the binary, but that's purely for the "suggestion" part. Once somebody decides they want to start importing that audit set, they'll add the URL directly to their config.toml, at which point migrations will start to become an issue.

It may be a moot point though, because registry fetching and suggestions aren't implemented yet, and will likely be implemented after `cargo vet aggregate`.

**Comment by str4d** [comment]
`cargo vet aggregate` has now been implemented in `main`, so I've opened #347 with our aggregated audit set. This issue can probably be closed after the next published release.

**Comment by bholley** [comment]
Thanks! We can probably go ahead and close it now, since aggregate itself has shipped. Still need to implement registry suggestions themselves though.
