### ISSUE TITLE
Move audit-as-crates-io to the policy table and implement `cargo vet regenerate`

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#193]
At the moment, `audit-as-crates-io` is its own separate table in `config.toml`, and the workflow involves copy-pasting a suggested version of that table into the file. It would be semantically cleaner to have this information (which pertains to nominally-first-party crates) in the policy table. This makes the copy-paste suggestion less viable, but it would actually be nicer anyway for the tool to take care of changing `config.toml`.

This leaves us with three "fixup" commands (regenerate-unaudited, accept-criteria-change, and this new thing). I think we should merge all of these into a single top-level `cargo vet regenerate` command with subcommands for each (`cargo vet regenerate unaudited`, `cargo vet regenerate imports`, and `cargo vet regenerate audit-as-crates-io`).

Marking this as high-priority because I would rather not check the current `audit-as-crates-io` table into m-c, which means this change blocks the next rev-bump.

**Comment by Gankra** [comment]
Some loose thoughts on audit-as-crates-io I need to braindump somewhere:

Currently it very aggressively transforms the crate into "completely third-party" for anything that asks. Arguably, this means the package *shouldn't have a policy anymore* because it won't be fed through resolve_first_party... except it does still have dev-deps, and should still be processed by resolve_dev.

Still, `policy.criteria` is nonsensical in this state and `policy.dependency_criteria` is only half-enabled in this state.

This is a new unique scenario -- a third-party with dev-deps. This is actually *asserted against* in resolve_third_party, so some code is *definitely* wrong and needs to be adjusted. I'm like 70% sure that we mishandle this case in DepGraph::new itself, although I forget why. I just remember noting that in the back of my head when I implemented resolver v3.

Thankfully we do still have the distinciton of is_workspace_member separate from third_party so most of the code will organically handle this situation correctly because dev-deps are mostly determined by is_workspace_member and not is_third_party.

I suppose it's an open question if workspace-members should be allowed for audit-as-crates-io. I am inclined to say yes if-only because what exactly "is" or "isn't" a workspace-member is mildly arbitrary when you do a lot vendoring in the ways mozilla does. Maybe I'm wrong though.

We definitely need tests for audit-as-crates-io, it should not be deployed until we have some.

**Comment by Gankra** [comment]
gonna do this in two parts -- one that makes the tables/semantics right that we can land quickly so m-c can get all the recent updates, then a second round that reworks the UX to be more magical. For the m-c update one of us will just have to manually add all the audit-as-crates-io entries.
