### ISSUE TITLE
Certify after a version bump should remove a pre-existing exemption

### ISSUE THREAD

**Issue by eqrion** [mozilla/cargo-vet#262]
Ran into this while updating the version of a crate that had never been audited before. I performed the version bump, certified the new version, and then had to manually remove the exemption from config.toml. I was told by @bholley that `cargo vet` should attempt to remove an exemption in this case and is likely being confused by the version bump.

STR:
```bash
mkdir test
cd test

cargo init --library
# add wast 43.0.0
vim Cargo.toml
cargo vet init
# note exemptions.wast exists in config.toml

vim Cargo.toml # bump wast to 44.0.0
cargo update
cargo vet # fails!

cargo vet certify wast 44.0.0
cargo vet # succeeds!

# note exemptions.wast 43.0.0 still exists in config.toml
```

**Comment by mystor** [comment]
Currently the `cargo vet certify` call will remove the exemption when it's run, but we don't have any mechanism for automatically removing irrelevant exemptions when running `cargo vet`. That only happens when you run `cargo vet regenerate exemptions` explicitly.

We were considering doing this implicitly after `cargo vet` in #119, but it was closed because of the existing behaviour of removing matching exemptions in `cargo vet certify` (https://github.com/mozilla/cargo-vet/issues/119#issuecomment-1171668106). Perhaps this particular gap is a reason to re-open that issue.

**Comment by bholley** [comment]
The middle ground here would be that we don’t do a full regenerate, but make certify's exemption-removal a bit smarter by having it check if other versions of the certified crate are still needed on the exemption list. This might assuage @Ganka's concerns about wholesale deployment of `regenerate exemptions`.

**Comment by Gankra** [comment]
> We could also lean on the side of doing a stricter version which is only allowed to remove existing exemptions which aren't required to keep the vet passing, rather than doing a full regenerate, though I don't know quite how tricky that would be to implement off the top of my head.

This is the code I ripped out in #224, in general it's extremely difficult to identify if an entry is "needed" or not without simply removing it and checking if things break (because you can have "useless" audits or "overbroad" audits that make things seem useful but can be routed around in the end).

There's also hypothetical situations where you have two exemptions, and removing either one is fine, but removing both breaks your vet. In this case we can choose to arbitrarily delete one of them, or conservatively preserve both without a way to pick the "better" one (with a warning?). However detecting that this situation exists is quite difficult.

Now that nika's really optimized things, it might be viable to do a more surgically precise regenerate that:

* checks what state `check` is in
  * if it fails, we're in **inserter mode**
    * apply all the `suggests` as `exemptions`
    * sanity check that `check` passes now?
      * if the sanity check fails, bail?
    * now enter remove mode to gc
  * if it passes, we're in **remover mode**
    * in a loop, reruns `vet` with an exemption tentatively removed to find candidate useless entries
    * remove the candidates
    * sanity check that `check` still passes?
      * if the sanity check fails, error out and tell the user about the candidates?

**Comment by eqrion** [comment]
Okay, so if I understand correctly, the general case here is hard. Would it be possible to detect the exact case I ran into when starting a project? The goal being to help projects getting started with `vet` and running into their first version bump.

Roughly, `cargo vet init` will create exemptions of the exact version of code you're using (e.g. `version = "0.2.0"`). Then when the crate is version bumped for the very first time, a `cargo vet certify` (which will autofill 0.3.0) will happen, which creates an audit of `version = "0.3.0"`.

After the certify, would it be possible to detect that there is a single version exemption of this crate, attempt to remove it, and see if that still passes? If it fails, no action is required and you could assume this is a more complicated situation.

**Comment by bholley** [comment]
The simple alternative, of course, is that we just do an implicit `regenerate exemptions` after `certify`. I know that @Gankra was worried about the algorithm not being tested enough, but maybe it's ok now, especially if we only do it after `certify` and not after every command? We could even skip it there are local modifications to `config.toml`, so that repairing any weirdness would always be one `git checkout supply-chain/config.toml` away.

**Comment by mystor** [comment]
If a single change caused multiple values to need to be certified, I'm not sure how great it would be to add exemptions for every other thing after a single call to `certify`. The advantage of doing it after a successful vet check is at least we know the call was successful before we regenerate exemptions, so aren't turning a failing vet into a succeeding one.

We could maybe do it after certify by running a vet check and only doing a regenerate exemptions if the check succeeded, I suppose?

**Comment by bholley** [comment]
> We could maybe do it after certify by running a vet check and only doing a regenerate exemptions if the check succeeded, I suppose?

Yes, this is more what I had in mind. Agree we should not be running an implicit `regenerate exemptions` when cargo vet isn't passing, since we only want to be removing entries not adding them.

**Comment by mystor** [comment]
I think `regenerate exemptions` should be accurate enough to run automatically if `vet` is successful after `certify` once #302 lands. We'll probably want to have a `--no-minimize-exemptions` flag or similar to prevent the behaviour if it causes folks issues, or is undesirable for some reason.

**Comment by bholley** [comment]
@mystor did you intend to close this? I didn't see the implicit regenerate step in that PR.
