### ISSUE TITLE
Support an array for the "who" field

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#320]
It's been pointed out that some large audits might be multi-person efforts. It wouldn't be a disaster to just put one of the names in there, or to use comma-separation, but I think it should be trivial with our existing machinery to support making the field an optional array, similar to the authors field in Cargo.toml.

This might also be a good exercise to kick the tires on format changes in the wild. How would an older version of cargo-vet behave when it encounters the array, and how do we want it to behave?

**Comment by mystor** [comment]
If we do a similar trick to what we do for criteria, of allowing either a string for one element or an array for multiple, we should be able to avoid needing to do any major machinery changes.

In terms of how an older version of `cargo-vet` would behave upon seeing an array, it would likely error out early while running with a parse error, pointing at the line in question.

Unfortunately, my quick testing revealed that the error is actually reported in completely the wrong place:

```
$ ./mach cargo vet
ERROR 
  × Failed to parse toml file
  ╰─▶ invalid type: sequence, expected a string for key `audits.synstructure.who` at line 1211 column 1
      ╭─[audits.toml:1210:1]
 1210 │ 
 1211 │ [[audits.xmldecl]]
      · ▲
      · ╰── here
 1212 │ who = "Henri Sivonen <hsivonen@hsivonen.fi>"
      ╰────
```

For whatever reason it appears to be being reported on the last audit in the file, rather than on the line which it failed to parse, though the error message is correct. I expect this is a toml crate issue, as we should be pulling the line and column information from there, but I haven't dug very deep yet.
