### ISSUE TITLE
FR: allow disambiguation of `audit-as-crates-io = true` crates not pulled through crates.io

### ISSUE THREAD

**Issue by gburgessiv** [mozilla/cargo-vet#360]
The vast majority of third-party crates that we pull in are downloaded through `crates.io`, and `audit-as-crates-io` Does The Right Thing for much of the remainder. That said, the behavior specified on [first-party code docs](https://mozilla.github.io/cargo-vet/first-party-code.html) leaves the potential for audit gaps:

```
[dependencies]
# If `anyhow` at this revision were published onto crates.io, it would appear as 1.0.66.
# However, the sources may not equal 1.0.66 as published.
# anyhow = { git = "https://github.com/dtolnay/anyhow", rev = "60e88002dcf7315487cbb2c724c66d2297c7bf46" }
anyhow = "=1.0.66"
```

Currently, the audit for the `git`-based `anyhow` would apply to the published `anyhow`, and vice-versa. It'd be nice if there were a mechanism for `cargo-vet` to differentiate between these somehow. Especially since the documentation notes:

"""
It's important to note that any audits for such derived crates still correspond to the crates.io version. This is what inspect and certify will display, and this is what you should review before certifying, since others in the ecosystem may rely on your audits when using the original crate without your particular modifications.
"""

Looking around, maybe #170 is relevant here?

**Comment by bholley** [comment]
I agree we should improve this.

When we designed the audit-as-crates-io feature, we were primarily thinking about `[patch]`/`[replace]`. The thinking was that any deviations from the published version would be first-party commits authored by the project owners, and thus safe by construction.

However, things get more fuzzy with git dependencies, which are sometimes just used as an out-of-tree variant of `[patch]`, but sometimes used to pull in pre-release versions of third-party crates. This creates some ambiguity around the rules of engagement, which we would ideally resolve by having cargo-vet keep track of things.

One way to characterize the situation is that cargo-vet operates at published-version granularity, but there is a finer level of intra-version granularity that can be expressed with git revs. We could potentially solve this by allowing audits to optionally correspond to git revs. Ideally we'd only allow this in the delta case, so that users are nudged to record the bulk of their audit findings in version space (which is more likely to be reusable by others in the ecosystem).

@mystor WDYT?

**Comment by mystor** [comment]
So the idea here is that there'd be some syntax by which we could use a git revision instead of a version number in audits? Would the assumption continue to be that git revisions are `audit-as-crates-io = false` unless specified otherwise?

Assuming I'm understanding correctly, the idea would be that if you specify a git revision which is `audit-as-crates-io = true`, it no longer is considered audited if there is an audit for the version in its manifest, and it now instead requires a specific git revision audit instead? This would be a breaking change unless we added some extra option for it somewhere. 

If we instead allow it to be audited by either the version number in the manifest or the git revision, I worry that will mean that we're missing potential differences, but it'd avoid being a breaking change.

**Comment by bholley** [comment]
I think a breaking change here is ok as long as we bump the semver. It doesn’t affect the format or semantics of shared data (assuming imports just drop audits with unknown fields?) so projects can just address it when they decide to pull in a new version of the tool.

**Comment by bholley** [comment]
And to be precise, the new requirement would be: if a project is pulled in by git rev and specified in policy as audit-as-crates-io=true, we require a delta audit chain that terminates in the imported hash.

**Comment by mystor** [comment]
Hmm, if we continue to use the `delta` field name that we currently use, it may cause imports to actually fail, as we changed the format in a way which causes a parsing error, rather than falling over gracefully and dropping a specific audit entry :-/. We don't really have support for doing semi-granular parsing of these files so that we can drop parts of the file which fail to parse in that situation right now, so it'd end up failing to import the entire audits.toml file in that case.

If we did it with new fields, it'd potentially cause an error due to a missing `delta` field of some kind.

**Comment by mystor** [comment]
We could potentially release a new patch for the current version which relaxes the parsing behaviour much more for imports, and makes potential errors into warnings in more cases for them, and then wait for folks to start using that before we make any larger changes to the format like this, so that we avoid that potential risk.

We need to keep stricter parsing on for local audits files though, because we'll be re-writing those.

**Comment by bholley** [comment]
Releasing a semantically compatible version with relaxed import parsing sounds like a good idea. I don’t think an extended waiting period will buy us much though, because most people are presumably using a pinned version in CI and are unlikely to organically upgrade.

I’m ok with a few bumps in the road given that we’re relatively early in the adoption cycle.

**Comment by mystor** [comment]
Relaxed parsing is now complete (#367), so the import concerns should hopefully be less of an issue going forward.

I've been thinking about this a bit more, and I think we might end up needing git versions to look something like `1.0.0 @ git:84772bd8b50d358ddc30a878d111944c2043b532` when in the file, such that they also contain the version number. The `git:` part is technically unnecessary right now, but will give us a framework to build on if we need to add other version variants in the future (e.g. if we use it for separate registries or other VCSes)

This would effectively act like a nonstandard semver extension like semver's prerelease syntax, except that it would be ordered after `1.0.0` in terms of releases, rather than before it. This allows the type to properly participate in delta recommendations, and be ordered in a more predictable way relative to other audits. The hashes would probably be sorted alphabetically, as there's no real way we can really give them an ordering beyond that, as we're not looking at the actual commits.

It's also a bit unclear how violations would work with git versions. That being said, given the somewhat-niche use-cases, it's probably OK if you can't specify a violation for a git version (though we could make violations for the base version match? violation syntax semantics is already a bit hairy especially around prereleases, so leaving it as a figure-out-later problem is probably fine).

**Comment by bholley** [comment]
This is now implemented, but will require a carefully-managed rollout, since it makes a breaking change to the audit file format and thus will break the import ecosystem as-is. The plan is to do a semantically-compatible dot release that relaxes the import parsing (simply discarding audits it can't parse), migrate all the known instances to that version, and then do a major release with this feature, which consumers can adopt at will.

**Comment by bholley** [comment]
I've opened PRs against the bytecode alliance and ISRG to upgrade to 0.3.1. The zcash CI doesn't pin a version (just uses whatever `cargo install cargo-vet` produces), so will pick this up automatically. Of the projects in the registry, that leaves @EmbarkStudios, where I believe the actual instance is private. @repi, can you bump to 0.3.1 internally so we don't break you with the next major release?

**Comment by repi** [comment]
@bholley thanks for the heads up! have done it.
