### ISSUE TITLE
Entries for third-party crates in the policy table should be version-associated

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#379]
In #363, we're removing `dependency-criteria` from the audit table. In its place, we're allowing third-party crates to appear as keys in the policy table. In that issue, @hpenne [pointed out](https://github.com/mozilla/cargo-vet/issues/363#issuecomment-1396580326) that this loses some precision since the usage of a crate referenced in a `dependency-criteria` downgrade could change.

I don't think it's super likely, but conceptually it does seem to me that entries for third-party crates in the policy table should be associated with specific versions. My strawman put for the semantics is that policy entries for third-party crates need to have the version as part of the key, e.g. `[policy.foo-1.2.3]`. To avoid the footgun where an update unintentionally causes such entry to become inapplicable, we can require that if you have a policy entry for one version of a third-party crate, you must have one for all versions that appear in the crate graph.

@mystor WDYT?

**Comment by mystor** [comment]
We could do something like that. I think it'd probably be written like `[policy.foo."v1.2.3"]` or similar.

One thing which is slightly awkward about this approach is that we already have `audit-as-crates-io` in the policy table, which in general should apply to all versions and marks a crate as third-party, though I suppose we could require enumerating the versions to specify `audit-as-crates-io` as well.

**Comment by bholley** [comment]
> One thing which is slightly awkward about this approach is that we already have `audit-as-crates-io` in the policy table, which in general should apply to all versions and marks a crate as third-party, though I suppose we could require enumerating the versions to specify `audit-as-crates-io` as well.

Didn't #366 enforce that `audit-as-crates-io` only be used on first-party crates?

**Comment by mystor** [comment]
It's possible that there are multiple versions of a crate in the tree, one of which is "first-party" and needs to be marked with `audit-as-crates-io`, and the other is "third-party" and is on crates.io. We also start treating crates which are marked as `audit-as-crates-io = true` as-if they were "third-party" in most of the codebase.

**Comment by bholley** [comment]
I see. I guess my mental model is that the non-versioned entries would apply to first-party crates and the versioned entries would apply to third-party crates. So if you set `policy.foo.audit-as-crates-io = true`, that would apply to one or more first-party version and force them to be treated as third-party versions, at which point the rules around consistently-specifying dependency-criteria across active third-party versions would apply.

**Comment by afranchuk** [comment]
Are there any good real-life examples I can look at where people are using `dependency-criteria` to meet/configure particular goals? I'm wondering whether it would be more ergonomic to, instead of specifying separate tables of crate versions (i.e. `crate.version.policy`), specify a set of versions that should all use a particular policy and change the crates to specify an array of policies (e.g. `crate[].policy`, with `policy` optionally having a `versions` array).

I think the latter would be more ergonomic if it's likely/common for the same policy to be applied to the accepted versions of the crates (as opposed to copying the same thing repeatedly in the former case). The latter is also a "superset" of the ergonomics of the former, since you can still separate per-version policies if you want.

**Comment by bholley** [comment]
> Are there any good real-life examples I can look at where people are using `dependency-criteria` to meet/configure particular goals?

There are a few in our [config.toml](https://searchfox.org/mozilla-central/rev/cf3af6bb6657278880f8baf38435eeb8f2d5d86c/supply-chain/config.toml#70).

> I'm wondering whether it would be more ergonomic to, instead of specifying separate tables of crate versions (i.e. `crate.version.policy`), specify a set of versions that should all use a particular policy and change the crates to (optionally) specify an array of policies (i.e. `crate[].policy`, with `policy` optionally having a `versions` array).
> 
> I think the latter would be more ergonomic if it's likely/common for the same policy to be applied to the accepted versions of the crates (as opposed to copying the same thing repeatedly in the former case). The latter is also a "superset" of the ergonomics of the former, since you can still separate per-version policies if you want.

I suspect that, for the case where we're putting this information in `config.toml`, the ergonomics will be a wash because you'll mostly just have a single version. When you upgrade the crate from version `X` to version `Y`, you'll just simultaneously tweak the version in the existing entry (because, unlike audits, `config.toml` is repo-private and doesn't need to be append-only).

No strong priors on either of the two syntactic approaches. Would need to think through the interaction with the requirement that third-party policy entries specify a version, and the edge case where some versions are first-party and others are third-party.

**Comment by afranchuk** [comment]
I was going to implement a scheme like `[policy.foo."v1.2.3"]`, but realized that in the presence of continued support for `[policy.foo]` it will be kind of messy.

This is because in the TOML data model those together would unroll
```toml
[policy.foo]
criteria = "safe-to-deploy"

[policy.foo."v1.2.3"]
criteria = "safe-to-run"
```
to (the equivalent):
```toml
[policy.foo]
criteria = "safe-to-deploy"
"v1.2.3" = { criteria = "safe-to-run" }
```
So when deserializing, we're left with searching through the keys to find those which match a version pattern and treating them differently.

---
Some alternatives:

### `version` table
```toml
[policy.foo]
criteria = "safe-to-deploy"

[policy.foo.version."1.2.3"]
criteria = "safe-to-run"
```
which turns to
```toml
[policy.foo]
criteria = "safe-to-deploy"
version = { "1.2.3" = { criteria = "safe-to-run" } }
```
The naive implementation for this would be a bit awkward, as you'd end up with `PolicyEntry` containing another map to `PolicyEntry`. It shouldn't be recursive, it should only allow `version` at the top level, so a better implementation would use separate types for those (likely just composing the versioned policy entry type into the top-level type).

### Policies as an array (as stated previously)
```toml
[[policy.foo]]
criteria = "safe-to-deploy"

[[policy.foo]]
version = "1.2.3" # could allow arrays, too
criteria = "safe-to-run"
```
This has the downside of not properly representing the uniqueness of policy entries: someone could define a particular version multiple times (including the "no version" case).

### Empty version for top-level (first-party) policies
```toml
[policy.foo.""] # or [policy.foo.any], [policy.foo.first-party], [policy.foo.direct]?
criteria = "safe-to-deploy"

[policy.foo."1.2.3"]
criteria = "safe-to-run"
```
This structure is more consistent, but makes the no-version policy a bit awkward and still requires a "keyword" that has special treatment (though since the versions are semver at least you can guarantee no conflict).

---
My preference is probably the version table, as I'd prefer the data constraints be represented in TOML itself rather than implementing them as an additional validation step.

**Comment by bholley** [comment]
Version table SGTM. We can require that `version` entries exist only for third-party crates in the project graph. I agree it should be a separate subtype that only supports `dependency-criteria`.

I'm a little torn as to whether we should introduce a separate explicit representation for this kind of weakening per #381, which would eliminate the only use-case for cramming third-party information into the policy table. But I think that's probably over-designing it at this stage, and we can just do the simple and intuitive thing for now.

**Comment by afranchuk** [comment]
After some discussion with @mystor, we're thinking that since the versioned policies can only (currently) have `dependency-criteria` defined, the rule will be:
> If an unversioned crate policy specifies `dependency-criteria`, that crate cannot be present as a third-party crate in the graph. Otherwise, the unversioned crate policy cannot have `dependency-criteria` specified and (to apply the desired `dependency-criteria`) versioned policies must be specified for each crate version in the graph.
