### ISSUE TITLE
Parse validation for git versions might be too lax

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#385]
Over in https://phabricator.services.mozilla.com/D167275, an engineer submitted an entry that looks like this:

```
delta = "0.5.0 -> 0.5.0@git:a990c93#a990c93ec64eeab78f2292763d0715da9dba1d59"
```

I'm guessing it was an accident during hand-editing, but seems like cargo-vet should eagerly reject such entries from the local audit file.

**Comment by mystor** [comment]
This should be simple enough to fix - we'll want to check the length of the hash, and that every character is a lowercase hex digit, around here:

https://github.com/mozilla/cargo-vet/blob/7bf2a5e707a28f32e689778cd03d84861dc35105/src/format.rs#L70

TBH I don't know if cargo supports sha256 git repositories right now (I'm guessing not, because libgit2 doesn't seem to: https://github.com/libgit2/libgit2/discussions/5840), so we can probably hold off on supporting that until it becomes an issue.
