### ISSUE TITLE
Potential sparse registry issues

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#466]
@badboy pinged me yesterday with the following error running `./mach vendor rust` on mozilla-central:

```
 0:19.61 Vet error: There are some issues with your policy.audit-as-crates-io entries
 0:20.62  related error: some audit-as-crates-io packages don't match published crates.io versions
  naga:0.12.0@git:b99d58ea435090e561377949f428bce2c18451bb
  wgpu-core:0.16.0@git:25cb9f61e9a6be572ee42536bbe57aa5f759a700
  wgpu-hal:0.16.0@git:25cb9f61e9a6be572ee42536bbe57aa5f759a700
  wgpu-types:0.16.0@git:25cb9f61e9a6be572ee42536bbe57aa5f759a700
```

This error is because cargo-vet thinks that naga-0.12.0 doesn't exist, but it was in fact published about two weeks before he got the error. After some debugging, we discovered that he had the sparse registry enabled (`[registries.crates-io] protocol = "sparse"` in `~/.cargo/config`), and reverting that fixed the problem.

I don't have a full grasp of the invariants of the sparse registry, but my guess here is that it's somehow only fetching releases for crates that are in the build graph. Since `naga` is nominally a first-party crate from cargo's perspective (it's as `git` override), it doesn't fetch the crate metadata, leading to this problem.

This may be somewhat mitigated by #464, but we'll still be scanning upstream crates for the description/repository fields, and so we'll want to make sure the mechanism we're using for that is reliable.

CC @mystor @afranchuk

**Comment by mystor** [comment]
I think I have brought this up before somewhere, but I'm having trouble finding the issue for it, so I may be misremembering.

Effectively with the sparse registry setup, the registry is served over HTTP from the crates.io domain, rather than being fully cloned as a git repository. 

The version of the `crates_index` crate which we currently use in-tree does not have any support for sparse indexes, though it appears that newer versions do have some minimal support (https://docs.rs/crates-index/latest/crates_index/struct.SparseIndex.html). There is a bug to track support for sparse registries (https://github.com/frewsxcv/rust-crates-index/issues/87) as well, though it appears as though they won't be able to be used transparently (https://github.com/frewsxcv/rust-crates-index/pull/101#issuecomment-1480461922).

If we decided to fetch the index ourselves, it wouldn't be too difficult to do. The index files are hosted at easy-to-predict paths (e.g. https://index.crates.io/ca/rg/cargo-vet for `cargo-vet`), and we could use the existing `crates_index::Crate::from_slice(...)` API to parse the result (https://docs.rs/crates-index/latest/crates_index/struct.Crate.html#method.from_slice).

**Comment by bholley** [comment]
Oh I see — so we use the non-sparse index unconditionally, irrespective of what's specified in `~/.cargo/config`.

So perhaps what happened to @badboy is that he was using the sparse registry for other day-to-day operations, which meant that it got stale, and uncovered a bug (cargo-vet not refreshing the index) that would rarely happen in practice because most people refresh their index frequently.

@mystor does that seem plausible?

**Comment by bholley** [comment]
I suppose this might dovetail with the conversation @afranchuk and I had on Matrix this morning.

**Comment by afranchuk** [comment]
I think #469 will mostly mitigate this issue (as the version of the crate will no longer be relevant).

**Comment by mystor** [comment]
I believe all of the non-sparse registry uses have been removed in #496, so we can close this out.
