### ISSUE TITLE
Consider treating multiple criteria on a single audit entry as independent

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#78]
As presently defined, every audit entry has explicit or implicit dependency_criteria which specify the conditions that the crate's dependencies must meet for the audit to be considered valid. The implicit default — which we expect to be used 99% of the time — sets all the dependency_criteria to the same criteria specified on the audit entry. So a regular audit for crate `foo` being `safe-to-deploy` is valid if and only if all of `foo`'s dependencies are also `safe-to-deploy`. And then you can occasionally use explicit dependency_criteria to do fancier stuff, like "this dependency isn't exposed to untrusted input so it just needs to be safe-to-run", or "this dependency handles bits on the wire and needs both safe-to-deploy _and_ crypto-reviewed". So far so good.

The question is how implicit dependency_criteria should interact with audit entries that specify multiple self criteria (e.g. an audit entry for foo with `criteria = ['a', 'b']`). If foo has a dependency which has only been audited for 'a', do we treat the criteria as interdependent and discard foo's audit entirely, or do we treat them as independent and partially evaluate it to 'a'?

So far we've been doing the former, but Tyler makes the point that this could be a hassle for projects that want to audit for a bunch of different granular criteria (since they'd have to create separate audit entries for each one to get the right semantics).

One thing we could do here would be to just desugar entries with multiple criteria into multiple entries, each with one criteria. This would still let you specify explicit joint dependency criteria if you really wanted to, but the implicit case would be more likely to line up with what people expect.

@Gankra wdyt?

**Comment by Gankra** [comment]
While bringing up tests I ran into some related cases that threw me off for a bit:

https://github.com/bholley/cargo-vet/blob/e095b3dc214cc9f457dde52fb9acb648a90e3439/src/tests.rs#L3220-L3231

Here we have some indirect-dev-dependency, which therefore only needs to be safe-to-run

We have 4 entries for this package:

```
A: v5-unaudited safe-to-deploy
B: v5-full safe-to-run
C: v5->10: safe-to-run
D: v5->10: safe-to-deploy
```

Certainly we can agree that (A) is unnecessary and regenerate-unaudited can be dropped here. **But what if (C) is missing? is B+D a valid chain for auditing v10 as safe-to-run, or does D fail to apply because it requires v5 to be safe-to-deploy?**

Also, you may note that I specifically use builtin_files_**minimal**_audited instead of builtin_files_**full**_audited as the base state the test is built off of. This effects the audit that indirect-dev-dependency's parent (dev-dependency) gets. `minimal` will notice it's dev-only and emit a safe-to-run audit. `full` will just blindly slap safe-to-deploy on everything.

If you drop A or D and make indirect-dev-dependency only safe-to-run then dev-dependency will "break" because its audit requires safe-to-deploy of its dependencies even though the parent policy only care about safe-to-run.

I was initially stymied by this test because I accidentally used `full` and was getting baffling results. The fact that even I was thrown off seems like a good indication that **we should definitely do this for implicit dependency-criteria and `implies`**.

I am coming around to the idea of doing this for multiple criteria **with only implicit dev-deps**. However I think these "optimizations" are unsound with any kind of explicit dependency-crtieria. There is no way to know what the user wants at this point, and would probably have incorrect implications for "stronger" or "weaker" criteria. 

i.e. if you say "serde is safe-to-deploy **if serde-utils is ULTRA-safe-to-deploy**" I think at that point it's unsound to determine that you can "downgrade" that into "serde is safe-to-run if serde-utils is safe-to-run". Otherwise it's not clear why you couldn't also just downgrade the ULTRA-safe-to-deploy requirement to safe-to-deploy!

**Comment by bholley** [comment]
So I think the mental model of the steps I'm proposing here still holds up to the above:
(1) Handle arrays: Desugar audit entries with `criteria = [a, b, c]` to separate audit entries for `a`, `b`, and `c`.
(2) Handle implies: For any audit entry with `criteria = x` where `x implies y`, create an identical entry for `criteria = y`.
(3) Handle implicit dependency criteria: For each entry with `criteria = x`, fill all the empty dependency criteria entries with `x`.

The key point here is that (3) happens last, so there's no funny business with transforming explicit dependency-criteria values with respect to `implies`.

**Comment by bholley** [comment]
Duping this to #189.
